<a href="https://colab.research.google.com/github/anishantony8/Deep-Learning/blob/main/FunctionalApi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [59]:
inputs = keras.Input(shape=(28,28))
flatten = keras.layers.Flatten()
dense1 = keras.layers.Dense(128, activation='relu')

dense2 = keras.layers.Dense(10, activation='softmax', name="category_output")
dense3 = keras.layers.Dense(1, activation='sigmoid', name="leftright_output")

In [60]:
x = flatten(inputs)
x = dense1(x)
outputs1 = dense2(x)
outputs2 = dense3(x)

model = keras.Model(inputs=inputs, outputs=[outputs1, outputs2], name="mnist_model")

In [61]:
model.summary()

Model: "mnist_model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_4 (InputLayer)           [(None, 28, 28)]     0           []                               
                                                                                                  
 flatten_3 (Flatten)            (None, 784)          0           ['input_4[0][0]']                
                                                                                                  
 dense_3 (Dense)                (None, 128)          100480      ['flatten_3[0][0]']              
                                                                                                  
 category_output (Dense)        (None, 10)           1290        ['dense_3[0][0]']                
                                                                                        

In [63]:
loss1 = keras.losses.SparseCategoricalCrossentropy(from_logits=False)
loss2 = keras.losses.BinaryCrossentropy(from_logits=False)
optim = keras.optimizers.Adam(learning_rate=0.001)
metrics = ["accuracy"]

losses = {
    "category_output": loss1,
    "leftright_output": loss2,
}

model.compile(loss=losses, optimizer=optim, metrics=metrics)

In [64]:
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# 0=left, 1=right
y_leftright = np.zeros(y_train.shape, dtype=np.uint8)
for idx, y in enumerate(y_train):
    if y > 5:
        y_leftright[idx] = 1

print(y_train.dtype, y_train[0:20])
print(y_leftright.dtype, y_leftright[0:20])

y= {"category_output": y_train,
    "leftright_output": y_leftright }

uint8 [5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]
uint8 [0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1]


In [65]:
model.fit(x_train, y=y, epochs=5,
          batch_size=64, verbose=2)

Epoch 1/5
938/938 - 6s - loss: 0.4970 - category_output_loss: 0.3023 - leftright_output_loss: 0.1947 - category_output_accuracy: 0.9151 - leftright_output_accuracy: 0.9290 - 6s/epoch - 6ms/step
Epoch 2/5
938/938 - 5s - loss: 0.2316 - category_output_loss: 0.1349 - leftright_output_loss: 0.0967 - category_output_accuracy: 0.9606 - leftright_output_accuracy: 0.9671 - 5s/epoch - 6ms/step
Epoch 3/5
938/938 - 4s - loss: 0.1696 - category_output_loss: 0.0947 - leftright_output_loss: 0.0749 - category_output_accuracy: 0.9717 - leftright_output_accuracy: 0.9747 - 4s/epoch - 4ms/step
Epoch 4/5
938/938 - 4s - loss: 0.1338 - category_output_loss: 0.0724 - leftright_output_loss: 0.0615 - category_output_accuracy: 0.9785 - leftright_output_accuracy: 0.9793 - 4s/epoch - 4ms/step
Epoch 5/5
938/938 - 5s - loss: 0.1119 - category_output_loss: 0.0592 - leftright_output_loss: 0.0527 - category_output_accuracy: 0.9823 - leftright_output_accuracy: 0.9821 - 5s/epoch - 5ms/step


In [66]:
predictions = model.predict(x_test)
len(predictions)

313/313 [==============================] - 1s 3ms/step


2

In [67]:
prediction_category = predictions[0]
prediction_lr = predictions[1]

pr_cat = prediction_category[0:20]
prediction_lr = prediction_lr[0:20]

labels_cat = np.argmax(pr_cat, axis=1)
labels_lr = np.array([1 if p >= 0.5 else 0 for p in prediction_lr])

In [68]:
print(y_test[0:20])
print(labels_cat)
print(labels_lr)

[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
[1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0]
