<a href="https://colab.research.google.com/github/anishantony8/Deep-Learning/blob/main/Tensorflow_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot

In [2]:
mnist = keras.datasets.mnist

In [3]:
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/usr/local/lib/python3.9/dist-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28) (60000,)


In [5]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = keras.models.Sequential([
        keras.layers.Flatten(input_shape=(28,28)),
        keras.layers.Dense(128,activation='relu'),
        keras.layers.Dense(10)
    ]
)

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = keras.optimizers.Adam(learning_rate=0.002)
metrics = ['accuracy']

In [12]:
model.compile(loss=loss,optimizer=optimizer,metrics=metrics)

In [13]:
batch_size = 64
epochs = 5

In [14]:
model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,shuffle=True,verbose=2)

Epoch 1/5
938/938 - 4s - loss: 0.2542 - accuracy: 0.9265 - 4s/epoch - 5ms/step
Epoch 2/5
938/938 - 4s - loss: 0.1114 - accuracy: 0.9670 - 4s/epoch - 4ms/step
Epoch 3/5
938/938 - 5s - loss: 0.0762 - accuracy: 0.9767 - 5s/epoch - 5ms/step
Epoch 4/5
938/938 - 3s - loss: 0.0577 - accuracy: 0.9819 - 3s/epoch - 4ms/step
Epoch 5/5
938/938 - 4s - loss: 0.0458 - accuracy: 0.9855 - 4s/epoch - 4ms/step


In [15]:
model.evaluate(x_test, y_test, batch_size=batch_size, verbose=2)

157/157 - 1s - loss: 0.0856 - accuracy: 0.9754 - 542ms/epoch - 3ms/step


[0.08559633791446686, 0.9753999710083008]

In [24]:
# Option1:

In [17]:
predicted_model = keras.models.Sequential([model,keras.layers.Softmax()]) 

In [21]:
pred = predicted_model.predict(x_test)
pred0 = pred[8]

313/313 [==============================] - 1s 2ms/step


In [22]:
label0 = np.argmax(pred0)
print(label0)

6


In [25]:
predictions = model(x_test)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

tf.Tensor(
[1.7182110e-07 8.1633384e-09 3.4037388e-05 1.1524154e-03 4.3264663e-11
 2.6443401e-09 2.0550074e-13 9.9880546e-01 2.8317963e-06 5.0195149e-06], shape=(10,), dtype=float32)
7


In [26]:
predictions = model.predict(x_test, batch_size=batch_size)
predictions = tf.nn.softmax(predictions)
pred0 = predictions[0]
print(pred0)
label0 = np.argmax(pred0)
print(label0)

157/157 [==============================] - 1s 3ms/step
tf.Tensor(
[1.7182110e-07 8.1633384e-09 3.4037388e-05 1.1524154e-03 4.3264663e-11
 2.6443401e-09 2.0550074e-13 9.9880546e-01 2.8317963e-06 5.0195149e-06], shape=(10,), dtype=float32)
7


In [29]:
pred05 = predictions[0:5]
print(pred05.shape)
label05 = np.argmax(pred05, axis=1)
print(label05)

(5, 10)
[7 2 1 0 4]


In [31]:
np.argmax(pred05, axis=1)

array([7, 2, 1, 0, 4])